### Week 2 assignment


### Part I -  NumPy

In [3]:
import numpy as np
import pandas as pd

In [4]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [6]:
np.shape(iris_2d)

(150, 4)

#### 1. ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and   horizontally.

In [7]:
np.random.shuffle(iris_2d)

In [11]:
a = iris_2d[:75]
b = iris_2d[75:]
horizontal_stack = np.hstack((a,b))
vertical_stack = np.vstack((a,b))

In [12]:
horiz_stack

array([[4.4, 3.2, 1.3, 0.2, 6.8, 2.8, 4.8, 1.4],
       [5.5, 2.6, 4.4, 1.2, 5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8, 5.1, 3.5, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2, 6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5, 6. , 2.7, 5.1, 1.6],
       [5.1, 3.5, 1.4, 0.2, 4.9, 3.1, 1.5, 0.1],
       [5.7, 3. , 4.2, 1.2, 5. , 3.5, 1.6, 0.6],
       [4.7, 3.2, 1.3, 0.2, 4.4, 2.9, 1.4, 0.2],
       [6. , 2.2, 5. , 1.5, 6.7, 3.3, 5.7, 2.1],
       [7.7, 3.8, 6.7, 2.2, 7.7, 2.8, 6.7, 2. ],
       [6.7, 3.1, 5.6, 2.4, 6.2, 3.4, 5.4, 2.3],
       [6.9, 3.1, 5.4, 2.1, 6.9, 3.1, 4.9, 1.5],
       [6.3, 2.8, 5.1, 1.5, 5. , 2.3, 3.3, 1. ],
       [5.8, 2.7, 4.1, 1. , 4.6, 3.4, 1.4, 0.3],
       [5.6, 3. , 4.1, 1.3, 5.5, 4.2, 1.4, 0.2],
       [6.4, 2.9, 4.3, 1.3, 6. , 3. , 4.8, 1.8],
       [5.4, 3.9, 1.7, 0.4, 5.5, 2.4, 3.8, 1.1],
       [6.1, 3. , 4.9, 1.8, 6.4, 3.2, 5.3, 2.3],
       [4.9, 3.1, 1.5, 0.1, 6.8, 3. , 5.5, 2.1],
       [6.4, 2.7, 5.3, 1.9, 5.2, 3.4, 1.4, 0.2],
       [6.3, 2.3, 4.

In [13]:
verti_stack

array([[4.4, 3.2, 1.3, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [5.9, 3.2, 4.8, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [4.7, 3.2, 1.3, 0.2],
       [6. , 2.2, 5. , 1.5],
       [7.7, 3.8, 6.7, 2.2],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.4, 2.1],
       [6.3, 2.8, 5.1, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [5.6, 3. , 4.1, 1.3],
       [6.4, 2.9, 4.3, 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [6.1, 3. , 4.9, 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [6.3, 2.3, 4.4, 1.3],
       [4.5, 2.3, 1.3, 0.3],
       [6.9, 3.1, 5.1, 2.3],
       [7.7, 2.6, 6.9, 2.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [5.7, 2.6, 3.5, 1. ],
       [6.7, 3.3, 5.7, 2.5],
       [5.2, 4.1, 1.5, 0.1],
       [4.8, 3. , 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6.7, 3.1, 4.7, 1.5],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 2

#### 2. Find common elements between A and B.

In [14]:
common_elements = np.intersect1d(a,b)
common_elements

array([0.1, 0.2, 0.3, 0.4, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8,
       1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1,
       3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4,
       4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7,
       5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.9, 7.2, 7.7])

#### 3. Extract all numbers from A which are within a specific range. eg between 5 and 10.

In [ ]:
location = np.where((a>=5) & (a<=10))
filtered_values = a[location]
filtered_values

array([5.1, 5. , 7.2, 6. , 5.5, 6.7, 5. , 7.4, 6.1, 6.7, 5.6, 5. , 5.8,
       6.5, 5.1, 6.3, 5.1, 7.6, 6.6, 5.1, 6.1, 6.2, 5.4, 5.7, 5.4, 5.8,
       5.1, 5.8, 5.9, 5.1, 5.5, 5.5, 6.3, 5.6, 5.1, 7.7, 6.9, 5.1, 5.4,
       7.2, 5.8, 5. , 6.8, 5.9, 5.2, 5.4, 5.6, 6.4, 6.7, 5.7, 5.9, 5.5,
       7.1, 5.9, 5.5, 6.5, 5.5, 6.6, 6.1, 5. , 6.4, 5.3, 5.7, 5.6, 6.5,
       7.7, 6.7, 5.2, 6. , 5.1, 7.9, 6.4, 5.5, 5. , 6.9, 5.1, 5. , 5.2,
       6. , 5. , 6.3, 5.6, 6.3, 5.6, 5.7])

#### 4. ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [15]:
filtered_rows = np.where((iris_2d[:,2]>1.5) & (iris_2d[:,0] < 5.0))
filtered_rows
filtered_data = iris_2d[filtered_rows]
filtered_data

array([[4.7, 3.2, 1.6, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [4.8, 3.4, 1.9, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ]])

### Part II - Pandas

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

#### 1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             55 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

In [18]:
df.shape

(93, 27)

#### 2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [19]:
filtered_data = df[['Manufacturer','Model','Type']].iloc[::20]
filtered_data

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [20]:
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [21]:
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace = True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace = True)

<ipython-input-21-cef24ccc0fb5>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace = True)
<ipython-input-21-cef24ccc0fb5>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=Tr

In [22]:
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

#### 3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

In [23]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
row_sum_df = df[df.sum(axis = 1) > 100]
row_sum_df

0   1   2   3
1   28  31  30  14
2   28  11  30  38
3   38  13  28  37
6   24  32  29  19
9   31  21  29  36
10  32  22  37  13
11  31  38  23  10
13  27  38  31  16